credentials:
- name: /concourse/main/gcp_subnet_master_deploy_director_ipv4
  type: json
  value:
    name: bosh-integration0
    ip: 10.100.0.10
    cidr: 10.100.0.0/24
    gw: 10.100.0.1
    reserved_range: '10.100.0.2 - 10.100.0.9'
- name: /concourse/main/gcp_subnet_master_deploy_director
  type: json
  value:
    name: bosh-integration1
    ip: 10.100.1.10
    cidr: 10.100.1.0/24
    gw: 10.100.1.1
    reserved_range: '10.100.1.2 - 10.100.1.9'
- name: /concourse/main/gcp_subnet_master_deploy_director
  type: json
  value:
    name: bosh-integration2
    ip: 10.100.2.30
    ip2: 10.100.2.15
    cidr: 10.100.2.0/24
    gw: 10.100.2.1
    reserved_range: '10.100.2.2 - 10.100.2.9'
    static_range: '10.100.2.10 - 10.100.2.30'

- name: /concourse/main/gcp_subnet_1.x_deploy_director
  type: json
  value:
    name: bosh-integration3
    ip: 10.100.3.10
    cidr: 10.100.3.0/24
    gw: 10.100.3.1
    reserved_range: '10.100.3.2 - 10.100.3.9'
- name: /concourse/main/gcp_subnet_1.x_deploy_director_ipv4
  type: json
  value:
    name: bosh-integration4
    ip: 10.100.4.10
    cidr: 10.100.4.0/24
    gw: 10.100.4.1
    reserved_range: '10.100.4.2 - 10.100.4.9'
- name: /concourse/main/gcp_subnet_1.x_deploy_director
  type: json
  value:
    name: bosh-integration5
    ip: 10.100.5.30
    ip2: 10.100.5.15
    cidr: 10.100.5.0/24
    gw: 10.100.5.1
    reserved_range: '10.100.5.2 - 10.100.5.9'
    static_range: '10.100.5.10 - 10.100.5.30'